name: Main CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y npm

      - name: Install npm dependencies
        run: npm i

      - name: Run ESLint
        run: npx eslint ./src

      - name: Run Prettier check
        run: npx prettier ./src --check

      - name: Run build
        run: npm run build